<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>KontaktLibManager.SelfTest</RootNamespace>
    <AssemblyName>KontaktLibManager.SelfTest</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <Compile Include="..\..\src\KontaktLibManager\GlobalUsings.cs" LinkBase="Core" />
    <Compile Include="..\..\src\KontaktLibManager\Core\*.cs" LinkBase="Core" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="NWaves" Version="0.9.6" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.1" />
    <PackageReference Include="UMAP" Version="1.0.62830" />
    <PackageReference Include="HdbscanSharp" Version="3.0.1" />
  </ItemGroup>

</Project>
